module.exports = {
  USER_ADMIN: "Administrator",
  USER_STAFF: "Staff",
  USER_WARD: "Ward",
  DIMINISHING_FIXED_EQUAL_AMORTIZATION: "DIMINISHING_FIXED_EQUAL_AMORTIZATION",
  STRAIGHT_LINE_AMORTIZATION: "STRAIGHT_LINE_AMORTIZATION",
  PURGING_MONTHS_RECORDING: "purging_months_recording",
  WATER_BILLING_FLAT_RATE: "water_billing_flat_rate",
  WATER_BILLLING_RATE: "water_billing_rate",
  LATE_CHARGES_PENALTTY: "late_charges_penalty",
  ASSOCIATION_DUES_HOME_OWNER: "association_dues_home_owner",
  ASSOCIATION_DUES_LOT_OWNER: "association_dues_lot_owner",
  LOT_OWNER: "Lot Owner",
  HOME_OWNER: "Home Owner",
  WATER_BILLING: "Water Billing",
  ASSOCIATION_DUES: "Association Dues",
  LOT_STATUS_OCCUPIED: "Occupied",
  LOT_STATUS_VACANT: "Vacant",
  OPERATING_ROOM_NUMBER_OPTIONS: ["1", "2", "3", "4", "5", "6", "7", "OB"],
  ON_SCHEDULE: "ON SCHEDULE",
  ON_GOING: "ON GOING",
  IN_HOLDING_ROOM: "IN HOLDING ROOM",
  ON_RECOVERY: "ON RECOVERY",
  ON_RECOVERY: "ON RECOVERY",
  ON_SCHEDULE: "ON SCHEDULE",
  ELECTIVE_SURGERY: "Elective Surgery",
  EMERGENCY_PROCEDURE: "Emergency Procedure",
  BACKLOG: "Backlog",
  CHARGE_NURSE: "CHARGE NURSE",
  RECEIVING_NURSE: "RECEIVING NURSE",
  HOLDING_ROOM_NURSE: "HOLDING ROOM",
  TEAM_CAPTAIN_ANES: "TEAM CAPTAIN",
  PACU_ANES: "PACU",
  ON_DUTY_ANES: "24 HOURS",
  OPERATING_ROOMS: {
    "1": "Heritage OR 1",
    "2": "Heritage OR 2",
    "3": "Heritage OR 3",
    "4": "Heritage OR 4",
    "5": "Heritage OR 5",
    "6": "Heritage OR 6",
    "7": "Heritage OR 7",
    WT1: "West OR 1",
    WT2: "West OR 2",
    EC: "Eye Center",
    OB: "OB",
  },
  RECEIVING_MODULE: "RECEIVING MODULE",
  PRE_OPERATION_MODULE: "PRE OPERATION MODULE",
  POST_OPERATION_MODULE: "POST OPERATION MODULE",
  TIME_LOGS_MODULE: "TIME LOGS MODULE",

  SELF_PAY: "SELF-PAY", // service
  NBB_PHIC: "NBB-PHIC", // housecase
  PHILHEALTH: "PHILHEALTH", // housecase
  PHIC: "PHIC", // housecase
  PDAF: "PDAF",

  SEX_MALE: "Male",
  SEX_FEMALE: "Female",

  AGE_CATEGORY_17_BELOW: "17 Years and Below",
  AGE_CATEGORY_18_ABOVE: "18 Years and Above",

  OPERATION_TYPE_MINOR: "Minor",
  OPERATION_TYPE_MAJOR: "Major",
  OPERATION_TYPE_CESAREAN: "Cesarean",
  OPERATION_TYPES: ["Major", "Cesarean", "Minor"],
  SERVICE_GS: "GS",
  SERVICE_OB: "OB",
  SERVICES: [
    "OB",
    "GS",
    "ENT",
    "ORTHO",
    "OPHTHA",
    "IM",
    "PEDIATRICS",
    "DENTAL",
    "OPD",
    "RADIOLOGY",
    "URO",
  ],
};
